[package]
name = "space4x"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.11.3", features = ["dynamic_linking"] }
uuid = "1.5.0"
rand = "0.8.5"
ringbuffer = "0.15.0"
bevy_editor_pls = "0.5.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
